version: "3.9"

services:
  oracledb:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracledb_fred
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: "SenhaForte123"
      APP_USER: "appuser"
      APP_USER_PASSWORD: "AppSenha123"
    volumes:
      - /data/oracle-data:/mnt/oracle/oradata
