version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-08-03T04-33-23Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /data/miniodata:/data
    environment:
      MINIO_ROOT_USER: minio-root
      MINIO_ROOT_PASSWORD: Senha999!
    command: server /data --console-address ":9001"
    restart: unless-stopped